_target_: experiments.unfolding.wrappers.ConditionalAutoregressiveTransformerCFM

autoregressive_tr:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  out_channels: 32
  hidden_channels: 128

  num_blocks: 4
  num_heads: 4
  dropout_prob: null

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: 4
  out_channels: 32
  hidden_channels: 128

  num_blocks: 4
  num_heads: 4
  dropout_prob: null

mlp:
  _target_: experiments.baselines.mlp.MLP

  in_shape: 44
  out_shape: 4

  hidden_channels: 256
  hidden_layers: 4
