_target_: experiments.kinematics.wrappers.ConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: null
  out_channels: 4
  hidden_channels: 64

  num_blocks: 8
  num_heads: 8
  dropout_prob: 0.0

  increase_hidden_channels: 2

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: null
  out_channels: null
  hidden_channels: 64

  num_blocks: 6
  num_heads: 8
  dropout_prob: 0.0

  increase_hidden_channels: 2