_target_: experiments.kinematics.wrappers.JetConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: null
  out_channels: null
  hidden_channels: 64

  num_blocks: 4
  num_heads: 8
  dropout_prob: 0.0

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: null
  out_channels: null
  hidden_channels: 64

  num_blocks: 2
  num_heads: 8
  dropout_prob: 0.0
