# Conditional LGATr model configuration for Jet Tokens
# Each jet's 4 coordinates (E, px, py, pz) become 4 separate tokens of dimension 1

_target_: experiments.kinematics.jet_tokens_wrappers.ConditionalLGATrJetTokensCFM

net:
  _target_: lgatr.nets.LGATr
  in_mv_channels: 1
  in_s_channels: null    # Will be set dynamically in experiment
  out_mv_channels: 1
  out_s_channels: 4      # Output for all 4 coordinate components
  hidden_mv_channels: 16
  hidden_s_channels: 64
  num_blocks: 6
  attention:
    num_heads: 8
    embed_dim: null      # Will be computed from hidden channels
    dropout: 0.1
  activation: "gelu"

net_condition:
  _target_: lgatr.nets.LGATr
  in_mv_channels: 1
  in_s_channels: null    # Will be set dynamically in experiment
  out_mv_channels: null  # Will be set dynamically in experiment
  out_s_channels: null   # Will be set dynamically in experiment
  hidden_mv_channels: 16
  hidden_s_channels: 64
  num_blocks: 4
  attention:
    num_heads: 8
    embed_dim: null      # Will be computed from hidden channels
    dropout: 0.1
  activation: "gelu"

scalar_dims: [1, 2, 3]  # Which coordinate dimensions to handle with scalar outputs
                        # 1: log(pt), 2: eta, 3: log(m^2)

GA_config:
  signature: [1, 1, 1]  # 3+1 spacetime signature