_target_: experiments.unfolding.wrappers.ConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  out_channels: 4
  hidden_channels: 32

  num_blocks: 2
  num_heads: 4
  dropout_prob: 0.1

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: 4
  out_channels: null
  hidden_channels: 32

  num_blocks: 2
  num_heads: 4
  dropout_prob: 0.1

  pos_encoding: false