_target_: experiments.kinematics.wrappers.JetConditionalLGATrCFM

scalar_inputs: [0,2,3]
scalar_outputs: [0,3]

GA_config:
 beam_spurion: xyplane
 beam_mirror: true
 add_time_spurion: true
 input_spurions: true
 condition_spurions: true
 spurion_channels: false

net:
 _target_: lgatr.nets.ConditionalLGATr

 in_mv_channels: 1
 condition_mv_channels: null
 out_mv_channels: 1
 hidden_mv_channels: 16

 in_s_channels: null
 condition_s_channels: null
 out_s_channels: 4
 hidden_s_channels: 32

 num_blocks: 3
 dropout_prob: null

 attention:
  num_heads: 8
  multi_query: false
  increase_hidden_channels: 1
  head_scale: false

 crossattention:
  num_heads: 8
  multi_query: false
  increase_hidden_channels: 1
  head_scale: false

 mlp:
  increase_hidden_channels: 2

net_condition:
 _target_: lgatr.nets.LGATr

 in_mv_channels: 1
 out_mv_channels: null
 hidden_mv_channels: 16

 in_s_channels: 1
 out_s_channels: null
 hidden_s_channels: 32

 num_blocks: 2
 dropout_prob: null

 attention:
  num_heads: 8
  multi_query: false
  increase_hidden_channels: 1
  head_scale: false

 mlp:
  increase_hidden_channels: 2

defaults:
 - /base_attention@net.attention
 - /base_attention_condition@net_condition.attention
 - /base_cross_attention@net.crossattention
 - /base_mlp@net.mlp
 - /base_mlp@net_condition.mlp
