_target_: experiments.multiplicity.wrappers.MultiplicityConditionalTransformerWrapper

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  condition_channels: 4
  out_channels: null
  hidden_channels: 128

  num_blocks: 2
  num_heads: 4
  dropout_prob: null