_target_: experiments.unfolding.wrappers.ConditionalGATrCFM
force_xformers: '${training.force_xformers}'
mean_aggregation: true

net:
 _target_: gatr.nets.ConditionalGATr

 in_mv_channels: 1
 condition_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 8

 in_s_channels: 1
 condition_s_channels: 1
 out_s_channels: 1
 hidden_s_channels: 8

 num_blocks: 4
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null
 double_layernorm: false

 attention:
  num_heads: 4
  multi_query: false
  increase_hidden_channels: 2
  head_scale: false

 crossattention:
  num_heads: 4
  multi_query: false
  increase_hidden_channels: 2
  head_scale: false

 attention_condition:
  num_heads: 4
  multi_query: false
  increase_hidden_channels: 2
  head_scale: false

defaults:
 - /base_attention@net.attention
 - /base_attention_condition@net.attention_condition
 - /base_cross_attention@net.crossattention
 - /base_mlp@net.mlp
