_target_: experiments.unfolding.wrappers.ConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  condition_in_channels: 4
  out_channels: 4
  hidden_channels: 128

  num_blocks: 2
  num_heads: 8
  dropout_prob: null

  pos_encoding: false