_target_: experiments.unfolding.wrappers.ConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  condition_channels: 4
  out_channels: 4
  hidden_channels: 128

  num_blocks: 4
  num_condition_blocks: 4
  num_heads: 4
  dropout_prob: null
