_target_: experiments.unfolding.wrappers.SimpleConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 12
  out_channels: 4
  hidden_channels: 64

  num_blocks: 3
  num_heads: 4
  dropout_prob: 0.1

  pos_encoding: true

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: 4
  out_channels: 64
  hidden_channels: 64

  num_blocks: 2
  num_heads: 4
  dropout_prob: 0.1

  pos_encoding: true