_target_: experiments.multiplicity.wrappers.MultiplicityTransformerWrapper

net:
  _target_: experiments.baselines.Transformer

  in_channels: 4
  out_channels: null
  hidden_channels: 256

  num_blocks: 4
  num_heads: 4
  dropout_prob: null

  pos_encoding: false