_target_: experiments.multiplicity.wrappers.MultiplicityTransformerWrapper

net:
  _target_: experiments.baselines.Transformer

  in_channels: null
  out_channels: null
  hidden_channels: 64

  num_blocks: 2
  num_heads: 4
  dropout_prob: 0.1
