# transformer settings optimized by us
iterations: 100000
batchsize: 128

optimizer: Lion
weight_decay: 2

lr: 3e-5
scheduler: CosineAnnealingLR

lr_factor_framesnet: 1.0
weight_decay_framesnet: 0.0

defaults:
  - default
