exp_type: chained
exp_name: chained_sampling

use_mlflow: false

# Paths to the three previous experiment directories
# Each should contain config.yaml and models/model_run*.pt
experiment_paths:
  multiplicity: runs/multiplicity_experiment/run_name  # Path to multiplicity experiment directory
  jets: runs/jets_experiment/run_name  # Path to jets experiment directory  
  constituents: runs/constituents_experiment/run_name  # Path to constituents experiment directory

# Which run index to use for model loading from each experiment
model_run_indices:
  multiplicity: 0
  jets: 0
  constituents: 0

train: false  # No training in chained experiment
training: null

evaluate: true
evaluation:
  batchsize: 1024
  sample: true
  n_batches: -1
  save_samples: true
  load_samples: false

plot: true
plotting:
  fourmomenta: true
  jetmomenta: true
  jetscaled: false
  preprocessed: false
  observables: ["jet", "angle"]
  n_pt: 3
  correlations: false

defaults:
  - default
  - _self_