exp_type: chained
exp_name: chained_sampling

use_mlflow: false

# Paths to the three previous experiment directories
# Each should contain config.yaml and models/model_run*.pt
experiment_paths:
  multiplicity: /remote/gpu04/petitjean/high-dim-unfolding/runs/clean_mult_test/lgatr_33536  # Path to multiplicity experiment directory
  jets: /remote/gpu04/petitjean/high-dim-unfolding/runs/jets_long/new_tr_42234  # Path to jets experiment directory
  constituents: /remote/gpu04/petitjean/high-dim-unfolding/runs/params/S_pos_37577  # Path to constituents experiment directory

# Which run index to use for model loading from each experiment
model_run_indices:
  multiplicity: 0
  jets: 0
  constituents: 0

train: false  # No training in chained experiment
training: null

evaluate: true
evaluation:
  batchsize: 1024
  sample: true
  n_batches: -1
  save_samples: true
  load_samples: false

plot: true
plotting:
  fourmomenta: true
  jetmomenta: true
  jetscaled: false
  preprocessed: false
  observables: ["jet"]
  n_pt: 3
  correlations: false

defaults:
  - default
  - _self_