exp_type: chain
exp_name: chain_sampling

use_mlflow: false

# Paths to the three previous experiment directories
# Each should contain config.yaml and models/model_run*.pt
experiment_paths:
  multiplicity: /remote/gpu04/petitjean/high-dim-unfolding/runs/chain_long/mult_z_lgatr  # Path to multiplicity experiment directory
  jets: /remote/gpu04/petitjean/high-dim-unfolding/runs/chain_long/jets_z  # Path to jets experiment directory
  constituents: /remote/gpu04/petitjean/high-dim-unfolding/runs/chain_long/constituents_z_lgatr  # Path to constituents experiment directory

# Which run index to use for model loading from each experiment
model_run_indices:
  multiplicity: 0
  jets: 0
  constituents: 4

train: false  # No training in chain experiment
training: null

evaluate: true
evaluation:
  batchsize: 4096
  sample: true
  n_batches: -1
  save_samples: true
  load_samples: false

plot: true
plotting:
  fourmomenta: true
  jetmomenta: true
  jetscaled: false
  preprocessed: false
  observables: ["jet"]
  n_pt: 3
  correlations: false

defaults:
  - default
  - _self_