exp_type: chain
exp_name: chain_sampling

use_mlflow: false

# Paths to the three previous experiment directories
# Each should contain config.yaml and models/model_run*.pt
experiment_paths:
  multiplicity: /work/classic/hd_iv329-hdu/high-dim-unfolding/runs/chain/mult_z_1690432  # Path to multiplicity experiment directory
  jets: /work/classic/hd_iv329-hdu/high-dim-unfolding/runs/jets_long/sppem2_tr_long_1690196  # Path to jets experiment directory
  constituents: /work/classic/hd_iv329-hdu/high-dim-unfolding/runs/chain/constituents_z_1690430  # Path to constituents experiment directory

# Which run index to use for model loading from each experiment
model_run_indices:
  multiplicity: 0
  jets: 0
  constituents: 0

train: false  # No training in chain experiment
training: null

evaluate: true
evaluation:
  batchsize: 1024
  sample: true
  n_batches: -1
  save_samples: true
  load_samples: false

plot: true
plotting:
  fourmomenta: true
  jetmomenta: true
  jetscaled: false
  preprocessed: false
  observables: ["jet"]
  n_pt: 3
  correlations: false

defaults:
  - default
  - _self_