exp_type: classification

data:
 tagging_features: null
 boost_jet: false
 beam_reference: null
 two_beams: false
 add_time_reference: false
 mass_reg: 5e-3
 spurion_scale: 1
 max_particles: null
 momentum_float64: false
 train_test: [0.8,0.2]
 data_path: ???

evaluation:
 batchsize: 512
 save_roc: false
 eval_set: [val]
 save_predictions: true

plotting:
 roc: true
 loss: true
 score: true

defaults:
 - model: tag_transformer
 - training: tag_transformer
 - default
 - _self_
