exp_type: constituents
exp_name: simplecondtest

use_mlflow: false

eps1: 1e-5
eps2: 1e-10
cutoff: 15

data:
 data_dir: data/
 dataset: zplusjet
 length: -1
 train_val_test: [0.8, 0.05, 0.15]
 max_num_particles: null
 max_constituents: -1
 min_mult: 2
 pt_cut: 0.0
 add_pid: false
 pt_min: null
 mass: 1.0
 pos_encoding_dim: 8
 mult_encoding_dim: 0

cfm:
 embed_t_dim: 8
 embed_t_scale: 30.0
 coordinates: StandardJetScaledLogPtPhiEtaLogM2
 geometry:
  type: simple
  periodic: true
 transforms_float64: true
 masked_dims: []
 cosine_similarity_factor: 0.0
 self_condition_prob: 0.0
 add_jet: true
 add_mass: false
 scaling: [1.0, 1.0, 1.0, 1.0]
 gac: true
 weight: 0.0
 sort: false
 rescale: false

odeint:
 method: rk4
 rtol: 1e-5
 atol: 1e-5
 options:
  step_size: 0.01

train: true
training:
 iterations: 100000
 batchsize: 1024
 lr: 1e-3
 scheduler: CosineAnnealingLR
 validate_every_n_steps: 5000
 clip_grad_norm: 5.

evaluate: true
evaluation:
 batchsize: 4096
 classifier: false
 sample: true
 n_batches: -1
 eval_loss: []
 save_samples: false
 load_samples: false
 overfit: false

plot: true
plotting:
 fourmomenta: false
 jetmomenta: true
 jetscaled: false
 preprocessed: false
 observables: ["jet"]
 n_pt: 3
 correlations: false

defaults:
 - model: cond_tr_constituents
 - default
 - _self_