exp_type: multiplicity
exp_name: mult_nopid

use_mlflow: false

data:
 data_dir: data/
 dataset: zplusjet
 length: -1
 train_val_test: [0.8, 0.05, 0.15]
 max_num_particles: null
 diff: null
 max_constituents: -1
 min_mult: 2
 add_pid: false
 pt_min: null
 mass: 0.001
 pos_encoding_dim: 0
 mult_embedding_dim: 0

dist: 
 type: GaussianMixture
 n_components: 5
 diff: true

train: true
training:
 iterations: 100000
 batchsize: 16384
 lr: 1e-3
 validate_every_n_steps: 5000
 scheduler: CosineAnnealingLR

evaluate: true
evaluation:
 batchsize: 16384
 save_samples: false
 save_params: 0

plot: true
plotting:
 loss: true
 histogram: true
 n_distributions: 0
 diff: true
 corr: false
 components: false

defaults:
 - model: tr_multiplicity
 - default
 - _self_