exp_type: multiplicity
exp_name: mult_debug

data:
 data_dir: data/
 dataset: zplusjets
 length: 100000
 split: [0.8, 0.1, 0.1]
 rescale_data: false
 max_num_particles: 152

train: true
training:
 iterations: 100000
 batchsize: 128
 lr: 1e-3
 validate_every_n_steps: 500000000000
 force_xformers: false # 'false' runs on cpu and gpu, 'true' only runs on gpu but is much faster

evaluate: false
evaluation:
 batchsize: 128

plot: false

defaults:
 - model: tr_multiplicity
 - default
 - _self_