exp_type: multiplicity
exp_name: mult_gatr_debug

seed: 42

use_mlflow: false

data:
 data_dir: data/
 dataset: zplusjets
 length: -1
 split: [0.8, 0.1, 0.1]
 rescale_data: false
 max_num_particles: 152
 beam_reference: xyplane
 two_beams: true
 beam_token: true
 add_time_reference: true
 add_xzplane: false
 add_yzplane: false
 add_pid: false
 add_scalar_features: false
 reinsert_channels: false

dist: 
 type: GammaMixture
 n_components: 3

loss:
 type: cross_entropy
 smoothness: 2

train: true
training:
 iterations: 10000
 batchsize: 128
 lr: 1e-3
 validate_every_n_steps: 5000
 force_xformers: false # 'false' runs on cpu and gpu, 'true' only runs on gpu but is much faster

evaluate: true
evaluation:
 batchsize: 128

plot: true
plotting:
 n_distributions: 128

defaults:
 - model: gatr_multiplicity
 - default
 - _self_