exp_type: multiplicity
exp_name: mult_debug

data:
 data_dir: data/

train: true
training:
 iterations: 10
 batchsize: 128
 lr: 1e-3
 validate_every_n_steps: 5000
 force_xformers: false # 'false' runs on cpu and gpu, 'true' only runs on gpu but is much faster

evaluate: true
evaluation:
 batchsize: 128

plot: false

defaults:
 - model: tr_multiplicity
 - default