exp_type: multiplicity
exp_name: mult_debug

seed: 42

use_mlflow: false

data:
 data_dir: data/
 dataset: zplusjets
 length: -1
 split: [0.8, 0.1, 0.1]
 rescale_data: false
 max_num_particles: 152

train: true
training:
 iterations: 100000
 batchsize: 128
 lr: 1e-3
 validate_every_n_steps: 5000
 force_xformers: false # 'false' runs on cpu and gpu, 'true' only runs on gpu but is much faster

evaluate: true
evaluation:
 batchsize: 128

plot: true
plotting:
 n_distributions: 20

defaults:
 - model: tr_multiplicity
 - default
 - _self_