exp_type: jets
exp_name: simplecondtest

use_mlflow: false

data:
 data_dir: data/
 dataset: zplusjet
 length: -1
 train_val_test: [0.8, 0.1, 0.1]
 max_num_particles: null
 max_constituents: -1
 add_pid: false
 pt_min: null
 mass: 1.0
 pos_encoding_dim: 8
 mult_encoding_dim: 8

cfm:
 embed_t_dim: 8
 embed_t_scale: 30.0
 coordinates: StandardLogPtPhiEtaLogM2
 geometry:
  type: simple
  periodic: true
 transforms_float64: true
 masked_dims: []
 cosine_similarity_factor: 0.0
 self_condition_prob: 0.0
 add_constituents: false
 add_mass: false
 scaling: [1.0, 1.0, 1.0, 1.0]
 ot: false
 transpose: false

odeint:
 method: rk4
 rtol: 1e-5
 atol: 1e-5
 options:
  step_size: 0.01

train: true
training:
 iterations: 100000
 batchsize: 1024
 lr: 1e-3
 scheduler: CosineAnnealingLR
 validate_every_n_steps: 1000
 clip_grad_norm: 5.

evaluate: true
evaluation:
 batchsize: 4096
 classifier: false
 sample: true
 n_batches: -1
 eval_loss: []
 save_samples: false
 load_samples: false
 overfit: false

plot: true
plotting:
 fourmomenta: false
 jetmomenta: true
 jetscaled: false
 preprocessed: false
 observables: []
 n_pt: 3
 correlations: false

defaults:
 - model: cond_tr_jets
 - default
 - _self_