exp_type: unfolding
exp_name: unfolding_runs1

seed: 42

use_mlflow: false

data:
 data_dir: data/
 dataset: zplusjet
 num_data: 10000
 train_test_val: [0.8, 0.1, 0.1]
 pid_encoding: false
 max_num_particles: 152
 max_constituents: -1
 det_mult: -1
 add_spurions: true
 beam_reference: xyplane
 two_beams: true
 beam_token: true
 add_time_reference: true
 add_xzplane: false
 add_yzplane: false
 add_pid: false
 add_scalar_features: false
 reinsert_channels: false
 base_type: 4
 units: 10
 mass: 0.1

cfm:
 embed_t_dim: 8
 embed_t_scale: 30.
 hutchinson: true
 coordinates: StandardLogPtPhiEtaLogM2
 condition_coordinates: StandardLogPtPhiEtaLogM2
 geometry:
  type: simple
  periodic: true
 transforms_float64: true
 zero_condition: false
 masked_dims: []

odeint:
 method: rk4
 rtol: 1e-5
 atol: 1e-5
 options:
  step_size: 0.05

train: true
training:
 iterations: 100
 batchsize: 16
 lr: 3e-4
 scheduler: CosineAnnealingLR
 validate_every_n_steps: 5000
 force_xformers: false # 'false' runs on cpu and gpu, 'true' only runs on gpu but is much faster
 clip_grad_norm: 5.

evaluate: true
evaluation:
 batchsize: 64
 classifier: false
 sample: true
 n_batches: -1
 eval_loss: []

plot: true
plotting:
 log_prob: false
 fourmomenta: true
 jetmomenta: true
 preprocessed: true
 observables: []
 n_pt: 1

defaults:
 - model: cond_tr_unfolding
 - default
 - _self_