exp_type: zmumu
exp_name: zmumu_debug

data:
 n_jets: [1]
 data_path_1j: data/zmumu_1j.npy
 data_path_2j: data/zmumu_2j.npy
 data_path_3j: data/zmumu_3j.npy
 subsample: 100000
 train_test_val: [.4, .5, .1]
 base_type: 4

evaluation:
 nsamples: 1000

defaults:
- ttbar