_target_: experiments.unfolding.wrappers.ConditionalTransformerCFM

net:
  _target_: experiments.baselines.ConditionalTransformer

  in_channels: 4
  out_channels: 4
  hidden_channels: 64

  num_blocks: 4
  num_heads: 4
  dropout_prob: 0

net_condition:
  _target_: experiments.baselines.Transformer

  in_channels: 4
  out_channels: null
  hidden_channels: 64

  num_blocks: 2
  num_heads: 4
  dropout_prob: 0

  pos_encoding: false