_target_: experiments.unfolding.wrappers.ConditionalMLPCFM

net:
 _target_: experiments.baselines.MLP

 in_shape: 4
 out_shape: 4
 hidden_channels: 64

 hidden_layers: 2

net_condition:
 _target_: experiments.baselines.MLP

 in_shape: 4
 out_shape: 4
 hidden_channels: 64

 hidden_layers: 2